[SCHEMA CHANGE REQUEST] - Added referral status and dates for changed status
Free-Laborers/u-refer pull request #75
Opened 2021-11-07 21:12 UTC by Danny123234

2021-11-09 05:15 UTC, CosineP approved these changes

2021-11-09 05:16 UTC, CosineP commented
I assume this change typechecks which I assume means we don't yet touch these fields

2021-11-09 05:54 UTC, swjeong0825 requested changes
I think we don't need this enum. If we can use the Dates we have as a status hint, and use the contactedDate or contacted(boolean) variable to indicate that specifically.

2021-11-09 18:28 UTC, slustig210 requested changes

2021-11-09 18:28 UTC, slustig210 commented on backend/prisma/schema.prisma
> +  deletedDate    DateTime?
remove deletedDate, just use finishedDate

2021-11-09 18:33 UTC, slustig210 requested changes

2021-11-09 18:33 UTC, slustig210 commented on backend/prisma/schema.prisma
> +}
We can add a "CLOSED" enum for when someone else was hired (the JOB POST was closed!) so the rest of the candidates are no longer under consideration

2021-11-09 18:40 UTC, slustig210 commented on backend/prisma/schema.prisma
> +}
you should not be able to add a referral to a closed/deleted job post
and
you should not be able to edit a referral unless it is open

2021-11-09 21:04 UTC, slustig210 commented on backend/prisma/schema.prisma
> +  createdDate        DateTime    @default(now()) @db.Timestamp
i am not sure what db.Timestamp does in the first place. I commented it out

2021-11-11 19:10 UTC, slustig210 commented on backend/prisma/schema.prisma
> +}
check these out. Thoughts? Reviewed would use finishedDate as its date.

2021-11-13 17:14 UTC, slustig210 approved these changes

2021-11-14 03:17 UTC, closed without merging