Created env var UREFER_DB_PORT to set port for postgres for local doc…
Free-Laborers/u-refer pull request #82
Opened 2021-11-09 20:39 UTC by slustig210

…ker compose

@kritisingh0114 this should fix the problem

defaults postgres port to 5433, but u can set it using the UREFER_DB_PORT

2021-11-10 02:14 UTC, swjeong0825 requested changes
I got this error when I ran this branch: 
![image](https://user-images.githubusercontent.com/60114085/141037027-f81abd7d-0f7e-43cf-8192-55b38ece3bf6.png)

I ran the docker successfully with the main branch, so I think my docker is supposed to work fine with this change.

2021-11-10 02:15 UTC, swjeong0825 commented on docker-compose.yml
> +      - ${UREFER_DB_PORT:-5433}:5432
@slustig210 Do you have an idea about this? it seems like the file is failing from reading out the DATABASE_URL env field.

2021-11-10 14:06 UTC, rdonati commented
@swjeong0825 I got the same error. Turned out it was a single vs double quote thing in `run.sh`. Should be fixed now

2021-11-10 14:42 UTC, slustig210 commented
> Turned out it was a single vs double quote thing in `run.sh`.

Oops lol, gotta switch it in migrate reset then as well

2021-11-10 19:17 UTC, Danny123234 approved these changes

2021-11-11 04:35 UTC, swjeong0825 approved these changes
Everything looks good to me!

2021-11-11 04:35 UTC, merged