Adds eslint to frontend
Free-Laborers/u-refer pull request #85
Opened 2021-11-10 18:42 UTC by rdonati

STILL NEED TO ADD TO BACKEND..
Not working when I add a config file to the backend for some reason.. someone else feel free to give this a shot

Adds eslint to frontend, uses standard defaults (NOT Airbnb which a lot of people supposedly prefer)
Adds vscode config to autoformat on save

2021-11-10 21:17 UTC, Danny123234 approved these changes

2021-11-11 03:38 UTC, CosineP requested changes
A couple of notes. Please read this discussion I had with @swjeong0825. https://github.com/Free-Laborers/u-refer/pull/37#discussion_r736134593 . In general, I proposed a three-step process, because this is going to absolutely suck with merges. As a result of that, we should also do this for frontend and backend *together* to avoiding needing to get to a good merge point twice.

First, get everyone on the team onboard with eslint (does everyone use vscode? Do they all have eslint installed? (no)). This needs to happen first so we don't get thrashing between formatting styles.

Second, someone (you, clearly) should do a full pass of auto-formatting (like what you've done here, with caveats) *at a time where we have as few unmerged lines of code as possible*. You should do it synchronously, with everyone on board that there's few unmerged lines, and then merge as quickly as possible, and get everyone to pull, to avoid as much headache as possible.

Third, eslint validation can and should go in CI.

One other point I want to make: We should choose a style that most closely matches what we already have. In particular, I think most of the edits I see are single quotes to double quotes. I think we mostly use single quotes as-is. So we should simply keep doing that. Then, I am very pro semicolons, but if we find there are extremely few, relative to needed, I think it would be worth enforcing no semicolons as opposed to the opposite.

2021-11-11 03:38 UTC, CosineP commented on .vscode/settings.json
> +  "eslint.validate": ["javascript"]
i think we (also?) want typescript, typescriptreact

2021-11-11 03:38 UTC, CosineP commented on frontend/.eslintrc.js
> +    quotes: ["error", "double"],
Mentioned above. I'm advocating for single quotes not arbitrarily.

2021-11-11 03:38 UTC, CosineP commented on frontend/.eslintrc.js
> +    "no-unused-vars": "off",
Unused variables is imo one of the most useful lints out there. What issues with enums did we see? I think we have some enums which we never construct / read one value of, which actually *does* indicate a problem. Can we consider fixing, `// eslint-disable-next-line`-ing them, or at the very least, turning these to warnings?

2021-11-11 03:38 UTC, CosineP commented on frontend/.eslintrc.js
> +    "react/jsx-filename-extension": [1, { extensions: [".js", ".jsx", ".ts", ".tsx"] }] // should add ".ts" if typescript project
Who said anything about next.js? The advantage of keeping jsx to jsx/tsx is that .ts can use <> syntax, plus, that way the linter will ensure our file extensions are as-expected.

2021-11-16 20:04 UTC, closed without merging